resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/43.yaml

packages:
- .

extra-deps:
- effectful-2.5.1.0
- effectful-core-2.5.1.0
- strict-mutable-base-1.1.0.0
